# Generated by Django 4.2.6 on 2023-10-29 19:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="VoteResult",
            fields=[
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("total_vote", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menu",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
